cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views
# from shop import views as core_views
# from shop.forms import LoginForm

urlpatterns = [
    # path('signup/', core_views.signup, name='signup'),
    # path('login/', auth_views.login, {'authentication_form': LoginForm}, name='login'),
    # path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create')
]

shop/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'shop'

urlpatterns = [
    path('opt/', views.opt, name='opt'),
    path('', views.main, name='main'),
    path('categories/', views.categories, name='categories'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('payship/', views.payship, name='payship'),
    path('product_list/', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


# PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    # quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, label='Количество', coerce=int, widget=forms.Select(attrs={'class': "select", }))
    quantity = forms.CharField(label='', widget=forms.TextInput(attrs={'style': "width: 80px;", 'type': "number", 'class': "input", 'placeholder': "Количество", 'step': "1", 'value': "10"}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        quantity = int(cd['quantity'])
        cart.add(product=product, quantity=quantity, update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        quantity = int(item['quantity'])
        item['quantity'] = int(item['quantity'])
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': quantity, 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Корзина
{% endblock %}


{% block content %}
<section>
    <div class="container">
      <div class="row columns">
        <div class="column is-10 is-offset-1">
          <div class="card">
            <div class="card-content">
                <nav class="level">
                  <div class="level-left">
                    <div class="level-item">
                      <p class="subtitle">Ваша корзина</p>
                    </div>
                  </div>
                  <div class="level-right">
                    <div class="level-item">
                      {% with totail_items=cart|length %}
                          {% if cart|length > 0 %}
                            Товаров: {{ totail_items }}, на сумму {{ cart.get_total_price }} грн.
                            {% else %}Корзина пуста.
                          {% endif %}
                      {% endwith %}
                    </div>
                  </div>
                </nav>
                  <table class="table is-striped is-narrow is-hoverable is-fullwidth">
                      <thead style="">
                          <tr>
                              <th>Изображение</th>
                              <th>Товар</th>
                              <th>Кол-во</th>
                              <th></th>
                              <th>Цена</th>
                              <th>Стоимость</th>
                          </tr>
                      </thead>
                      <tbody>
                      {% for item in cart %}
                          {% with product=item.product  %}
                              <tr>
                                  <td>
                                      <a href="{{ product.get_absolute_url }}">
                                          <img src="{% if product.image1 %} {{ product.image1.url }} {% else %} {% static 'img/default.png' %} {% endif %}" style="height: 150px; width: 200px">
                                      </a>
                                  </td>
                                  <td>{{ product.name }}</td>
                                  <td>
                                      <form action="{% url "cart:cart_add" product.id %}" method="post">
                                          {% csrf_token %}
                                          {{ item.update_quantity_form.quantity }}
                                          {{ item.update_quantity_form.update }}
                                          <input type="submit" value="Обновить" class="button is-link">
                                      </form>
                                  </td>
                                  <td>
                                      <a href="{% url "cart:cart_remove" product.id %}" class="button is-danger">Убрать</a>
                                  </td>
                                  <td>{{ item.price }} грн.</td>
                                  <td>{{ item.total_price }} грн.</td>
                              </tr>
                          {% endwith %}
                      {% endfor %}
                      <tr style="">
                          <td colspan="5"><b>Всего</b></td>

                          <td colspan="num"><b>{{ cart.get_total_price }} грн.</b></td>
                      </tr>
                      </tbody>
                  </table>
              <p class="text-right">
                  <a href="{% url "shop:categories" %}" class="button is-info">Продолжить покупки</a>
                  <a href="{% url "orders:order_create" %}" class="button is-success">Заказать</a>
              </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}