cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views
# from shop import views as core_views
# from shop.forms import LoginForm

urlpatterns = [
    # path('signup/', core_views.signup, name='signup'),
    # path('login/', auth_views.login, {'authentication_form': LoginForm}, name='login'),
    # path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'shop'

urlpatterns = [
    path('opt/', views.opt, name='opt'),
    path('', views.main, name='main'),
    path('categories/', views.categories, name='categories'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('payship/', views.payship, name='payship'),
    path('product_list/', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    image = models.ImageField(upload_to='images', blank=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(max_length=200, blank=True)
    country = models.CharField(max_length=100, default='Дубаи')
    articul = models.DecimalField(max_digits=10, decimal_places=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    price2 = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image1 = models.ImageField(upload_to='products', blank=True)
    image2 = models.ImageField(upload_to='products', blank=True)
    image3 = models.ImageField(upload_to='products', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class Text(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    title = models.CharField(max_length=100)
    title2 = models.CharField(max_length=100)
    text1 = models.TextField(blank=True)
    text2 = models.TextField(blank=True)
    text3 = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Main(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='images', blank=True)

    def __str__(self):
        return self.name


class Card(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=100, default='#')
    image = models.ImageField(upload_to='cards', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    username = forms.CharField(label='', widget=forms.TextInput(attrs={'class': "input is-large", 'placeholder': "Логин", 'autofocus': ""}))
    # first_name = forms.CharField(label='', max_length=30, required=False,
    #     widget=forms.TextInput(attrs={'name': 'Имя', 'class': "input is-large", 'placeholder': "Имя", 'autofocus': ""}))
    # last_name = forms.CharField(label='', max_length=30, required=False,
    #     widget=forms.TextInput(attrs={'class': "input is-large", 'placeholder': "Фамилия", 'autofocus': ""}))
    email = forms.EmailField(label='', max_length=254,
        widget=forms.TextInput(attrs={'class': "input is-large", 'placeholder': "Email", 'autofocus': ""}))
    password1 = forms.CharField(label='', widget=forms.TextInput(attrs={'type': "password", 'class': "input is-large", 'placeholder': "Пароль", 'autofocus': ""}))
    password2 = forms.CharField(label='', widget=forms.TextInput(attrs={'type': "password", 'class': "input is-large", 'placeholder': "Пароль ещё раз", 'autofocus': ""}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )
        # 'first_name', 'last_name', - removed


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='', widget=forms.TextInput(attrs={'class': "input is-large", 'placeholder': "Логин", 'autofocus': ""}))
    password = forms.CharField(label='', widget=forms.TextInput(attrs={'type': "password", 'class': "input is-large", 'placeholder': "Пароль", 'autofocus': ""}))

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Main, Card, Text
from cart.forms import CartAddProductForm
# from django.contrib.auth import login, authenticate
# from shop.forms import SignUpForm
# from django.shortcuts import redirect


def categories(request, category_slug=None):
    categories = Category.objects.all()

    context = {
        'categories': categories,

    }
    return render(request, 'shop/product/categories.html', context)


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    if request.method == 'GET':
        query = request.GET.get('q')
        if query:
            products = Product.objects.filter(name__contains=query)

    context = {
        'category': category,
        'categories': categories,
        'products': products,

    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    categories = Category.objects.all()
    context = {
        'categories': categories,
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)


# def signup(request):
#     if request.method == 'POST':
#         form = SignUpForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             login(request, user)
#             return redirect('shop:product_list')
#     else:
#         form = SignUpForm()
#     return render(request, 'signup.html', {'form': form})


def main(request):
    if Card.objects.order_by('-id')[:3]:
        last_three = Card.objects.order_by('-id')[:3]

        card1 = last_three[2]
        card2 = last_three[1]
        card3 = last_three[0]
    else:
        card1 = None
        card2 = None
        card3 = None
    image = Main.objects.reverse()[0]
    categories = Category.objects.all()

    context = {
        'categories': categories,
        'card1': card1,
        'card2': card2,
        'card3': card3,
        'image': image

    }
    return render(request, 'shop/main.html', context)


def about(request):
    text = Text.objects.get(pk=1)
    categories = Category.objects.all()
    context = {
        'text': text,
        'categories': categories,
    }
    return render(request, 'shop/about.html', context)


def payship(request):
    categories = Category.objects.all()
    text = Text.objects.get(pk=2)
    context = {
        'text': text,
        'categories': categories,
    }
    return render(request, 'shop/payship.html', context)


def contact(request):
    categories = Category.objects.all()
    text = Text.objects.get(pk=3)
    context = {
        'text': text,
        'categories': categories,
    }
    return render(request, 'shop/contact.html', context)


def opt(request):
    categories = Category.objects.all()
    text = Text.objects.get(pk=4)
    context = {
        'text': text,
        'categories': categories,
    }
    return render(request, 'shop/opt.html', context)

shop/templates/shop/about.html
{% extends 'shop/base.html' %}
{% block title %}
    О нас
{% endblock %}
{% block content %}
  <section class="hero">
        <div class="hero-body">
            <div class="container">
                <div class="column is-12">
                  <div class="content">
                    <h1 class="title has-text-centered">{{ text.title }}</h1>
                    <p style="color: black">{{ text.text1 }}</p>
                    <p style="color: black">{{ text.text2 }}</p>
                    <p style="color: black">{{ text.text3 }}</p>
                  </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html class="has-navbar-fixed-top" lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Мир ткани{% endblock %}</title>
  <link rel="icon" type="image/png" href="{% static 'img/icon.png' %}" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>
  <script language="JavaScript" type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
  <!-- Bulma Version 0.7.1-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
    <link rel="stylesheet" href="{% static 'css/forum.css' %}">
    <link rel="stylesheet" href="{% static 'css/hero.css' %}">
    <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
</head>
<body>

{% include 'shop/navbar.html' %}

{% block content %}
{% endblock %}

    <footer class="footer">
			<div class="container">
				<div class="content has-text-centered">
					<div class="columns is-mobile is-centered">
            <div class="columns">
              <div class="column is-4">
                <p>Телефоны:<br>
                +38 097 556 12 17<br>
                +38 073 737 31 61</p>
              </div>
              <div class="column is-4">
                <div class="content has-text-centered">
                  <p>
                    <a href="">
                        <i class="fab fa-facebook-square fa-2x"></i>
                    </a>

                    <a href="">
                        <i class="fab fa-instagram fa-2x"></i>
                    </a>
                  </p>
                </div>
              </div>
              <div class="column column is-4">
                <div class="field is-grouped is-grouped-multiline">
    							<div class="control">
    								<div class="tags has-addons">
    									<a class="tag is-link" href="https://ivanbochenko.github.io/">The source code is licensed</a>
    									<span class="tag is-light">© Bochenko I.А., 2018.</span>
    								</div>
    							</div>
    						</div>
              </div>
            </div>
					</div>
				</div>
			</div>
		</footer>
		<script async type="text/javascript" src="{% static 'js/bulma.js' %}"></script>
	</body>
</html>

shop/templates/shop/contact.html
{% extends 'shop/base.html' %}
{% block title %}
    Контакты
{% endblock %}
{% block content %}
  <section class="hero">
        <div class="hero-body">
            <div class="container">
                <div class="column is-12">
                    <h1 class="title has-text-centered">{{ text.title }}</h1>
                    <br>
                    <div class="columns">
                      <div class="column is-3">
                        <p style="color: black">{{ text.text1 }}</p><br>
                        <p style="color: black">{{ text.text2 }}</p><br>
                        <p style="color: black">{{ text.text3 }}</p><br>
                      </div>

                      <div class="column is-6">
                        <iframe width="600" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:EkzQstGD0LvQuNGG0Y8g0JDQvdC00YDRltGPINCc0LDQu9C40YjQutCwLCAyLCDQmtC40ZfQsiwg0KPQutGA0LDRl9C90LAsIDAyMDAwIjASLgoUChIJrQC-Z_zP1EAR5cXHOjQghq4QAioUChIJxaza4v3P1EARwI-JhqX9b18&key=AIzaSyBbE1jmk4DRRuQl7w7bch4rWVVOwtMKPzM" allowfullscreen></iframe>                      </div>
                      </div>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

shop/templates/shop/main.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
    <section class="hero">
        <figure class="image">
            <img src="{% if image %} {{ image.image.url }} {% else %} {% static 'img/default.png' %} {% endif %}">
        </figure>
    </section>

    <section class="section">
        <div class="container has-text-centered">
            <h2 class="title">{{ image.name }}</h2>
            <p>{{ image.text }}</p>

            <div class="columns is-centered" >
                {% if card1 %}
                <div class="column">
                    <div class="card" style="height: 500px">
                        <div class="card-image">
                            <figure class="image">
                              <a href="{{ card1.link }}">
                    						<img style="height: 320px" src="{% if card1 %} {{ card1.image.url }} {% else %} {% static 'img/default.png' %} {% endif %}">
                    					</a>
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="media">
                                <div class="media-content has-text-centered">
                                    <h1 class="title is-4">{{ card1.name }}</h1>
                                </div>
                            </div>

                            <div class="content">
                                {{ card1.description }}
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% if card2 %}
                <div class="column">
                    <div class="card" style="height: 500px">
                        <div class="card-image">
                            <figure class="image">
                              <a href="{{ card2.link }}">
                    						<img style="height: 320px" src="{% if card2 %} {{ card2.image.url }} {% else %} {% static 'img/default.png' %} {% endif %}">
                    					</a>
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="media">
                                <div class="media-content has-text-centered">
                                  <h1 class="title is-4">{{ card2.name }}</h1>
                                </div>
                            </div>

                            <div class="content">
                              {{ card2.description }}
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% if card3 %}
                <div class="column">
                    <div class="card" style="height: 500px">
                        <div class="card-image">
                            <figure class="image">
                              <a href="{{ card3.link }}">
                    						<img style="height: 320px" src="{% if card3 %} {{ card3.image.url }} {% else %} {% static 'img/default.png' %} {% endif %}">
                    					</a>
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="media">
                                <div class="media-content has-text-centered">
                                  <h1 class="title is-4">{{ card3.name }}</h1>
                                </div>
                            </div>

                            <div class="content">
                              {{ card3.description }}
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        </div3

{% endblock %}

shop/templates/shop/navbar.html
{% load static %}

<nav class="navbar is-fixed-top is-white topNav">
			<div class="container">
				<div class="navbar-brand">
					<a class="navbar-item" href="{% url 'shop:main' %}">
						<img src="{% static 'img/мир-ткани.png' %}" width="130">
					</a>
					<div class="navbar-burger burger" data-target="topNav">
						<span></span>
						<span></span>
						<span></span>
					</div>
				</div>
				<div id="topNav" class="navbar-menu">
					<div class="navbar-start">

						<div class="navbar-item has-dropdown is-hoverable">
						  <a class="navbar-link" href="{% url 'shop:categories' %}">
						    Каталог
						  </a>
						  <div class="navbar-dropdown">
								{% for c in categories %}

								 <a class="navbar-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a>

							 {% endfor %}
						  </div>
						</div>
						<a class="navbar-item" href="{% url 'shop:about' %}">О нас</a>
						<a class="navbar-item" href="{% url 'shop:payship' %}">Оплата и доставка</a>
						<a class="navbar-item" href="{% url 'shop:contact' %}">Контакты</a>
						<a class="navbar-item" href="{% url 'shop:opt' %}">Оптовые поставки</a>
					</div>
					<div class="navbar-end">
						{% with totail_items=cart|length %}
							{% if cart|length > 0 %}
							<a class="navbar-item" href="{% url 'cart:cart_detail' %}">Корзина: {{ totail_items }}<i class="fas fa-shopping-cart"></i></a>
							{% endif %}
						{% endwith %}
						{% if products %}
						<div class="navbar-item">
	            <form method="GET" action="" id="searchform">
	                <input  id="searchbox" type="text" name="q" class="input" value="{{ request.GET.q }}" placeholder="Поиск...">
	            </form>
	          </div>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>

shop/templates/shop/opt.html
{% extends 'shop/base.html' %}
{% block title %}
Оптовые поставки
{% endblock %}
{% block content %}
  <section class="hero">
    <div class="hero-body">
        <div class="container">
            <div class="column is-12 is-offset-">
              <div class="content">
                <h1 class="title has-text-centered">{{ text.title }}</h1>
                <p style="color: black">{{ text.text1 }}</p><br>
                <p style="color: black">{{ text.text2 }}</p><br>
                <p style="color: black">{{ text.text3 }}</p><br>
              </div>
            </div>
        </div>
    </div>
  </section>
{% endblock %}

shop/templates/shop/payship.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% block title %}
    Оплата и доставка
{% endblock %}
{% block content %}
  <section class="hero">
    <div class="hero-body">
      <div class="container">
        <div class="column is-12">
          <div class="content">
            <h1 style="color: " class="title has-text-centered">{{ text.title }}</h1>
            <div class="columns">
              <div class="column">
                <p style="color: ">{{ text.text1 }}</p><br>

              </div>
              <div class="column is-3">
                <img style="height: 100px; width: auto;  display: block; margin: 0 auto;" src="{% static 'img/logo-privat24.png' %}"><br>

              </div>
            </div>
            <h1 style="color: " class="title has-text-centered">{{ text.title2 }}</h1>
            <p style="color: ">{{ text.text2 }}</p><br>
            <div class="">
              <img style="height: 75px; width: auto" src="{% static 'img/ship1.png' %}">
              <img style="height: 75px; width: auto" src="{% static 'img/ship2.png' %}">
              <img style="height: 75px; width: auto" src="{% static 'img/ship3.png' %}">
              <img style="height: 75px; width: auto" src="{% static 'img/ship4.png' %}">
            </div><br>
            <p style="color: ">{{ text.text3 }}</p><br>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}